name: Combined Workflow for SLSA Provenance, Verification, SBOM, and Policy Enforcement

on:
  push:
    branches: [main]

jobs:
  combined-workflow:
    runs-on: self-hosted
    env:
      HARNESS_ACCOUNT_URL: 'https://qa.harness.io'
      HARNESS_ACCOUNT_ID: 'ppbLW9YpRharzPs_JtWT7g'
      HARNESS_ORG_ID: 'SSCA'
      HARNESS_PROJECT_ID: 'SSCA_Sanity_Automation'
      HARNESS_API_KEY: ${{ secrets.SSCA_QA_API_KEY }}
      VAULT_ADDR: ${{ secrets.VAULT_URL }}
      DOCKER_CONFIG: $HOME/.docker

    steps:
      # Step 1: Checkout the main repository
      - name: Checkout Main Repository
        uses: actions/checkout@v3

      # Step 2: Clone Additional Repository
      - name: Clone Additional Repository
        run: |
          git clone https://github.com/nginxinc/docker-nginx.git
          echo "Cloned additional repository: docker-nginx"

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and Tag Docker Image
      - name: Build and Tag Docker Image
        run: |
          cd docker-nginx
          docker build -t reetika1999/github-service:latest -f ./stable/alpine/Dockerfile .
          echo "Docker image built and tagged as reetika1999/github-service:latest."

      # Step 5: Push the Docker Image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push reetika1999/github-service:latest
          echo "Docker image pushed to Docker Hub."

      # Step 6: Log in to Vault
      - name: Log in to Vault
        uses: hashicorp/vault-action@v2
        id: vault_login
        with:
          url: ${{ secrets.VAULT_URL }}
          method: token
          token: ${{ secrets.VAULT_TOKEN }}
          exportToken: true

      # Step 7: Set Vault Environment Variables
      # - name: Set Vault Environment Variables
      #   run: |
      #     echo "VAULT_ADDR=${{ secrets.VAULT_URL }}" >> $GITHUB_ENV
      #     echo "VAULT_TOKEN=${{ steps.vault_login.outputs.token }}" >> $GITHUB_ENV

      # Step 8: Run SLSA Provenance Action
      - name: Run SLSA Provenance Action
        uses: ./slsa-generation
        with:
          TARGET: 'reetika1999/github-service:latest'
          ATTEST: true
          KMS_KEY: 'cosign'
          
      - name: Run SLSA Verification Action
        uses: ./slsa-verification
        with:
          TARGET: 'reetika1999/github-service:latest'
          VERIFY: true
          KMS_KEY: 'cosign'

      # Step 9: Run SBOM Orchestration Action
      - name: Run SBOM Orchestration Action
        uses: ./sbom-generation
        with:
          TOOL: 'Syft'
          FORMAT: 'spdx-json'
          TARGET: 'reetika1999/github-service:latest'
          ATTEST: true
          KMS_KEY: 'cosign'

      # Step 10: Run SBOM Policy Enforcement
      - name: Run SBOM Policy Enforcement Action
        uses: ./sbom-policy-enforcement
        with:
          TARGET: 'reetika1999/github-service:latest'
          VERIFY: true
          KMS_KEY: 'cosign'
          POLICY_SET_REF: 'github_opa_policy'
