name: SLSA Provenance Workflow

# on:
#   push:
#     branches: [main]

jobs:
  run-ssca-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Log in to Vault
        uses: hashicorp/vault-action@v2
        id: vault_login
        with:
          url: ${{ secrets.VAULT_URL }}
          method: token
          token: ${{ secrets.VAULT_TOKEN }}
          
      - name: Set Vault Environment Variables
        run: |
          echo "VAULT_ADDR=${{ secrets.VAULT_URL }}" >> $GITHUB_ENV
          echo "VAULT_TOKEN=${{ steps.VAULT_TOKEN }}" >> $GITHUB_ENV
          
      - name: Run SLSA Provenance Action
        uses: ./slsa-provenance
        with:
          HARNESS_ACCOUNT_URL: 'https://reetika.pr2.harness.io'
          HARNESS_API_KEY: ${{ secrets.HARNESS_API_KEY }}
          HARNESS_ACCOUNT_ID: 'v7uYjYGtR4qIZAqh_Z-4DQ'
          HARNESS_ORG_ID: 'SSCA'
          HARNESS_PROJECT_ID: 'SSCA_Sanity_Automation'
          TARGET: 'reetika1999/ssca-manager:latest'
          ATTEST: true
          KMS_KEY: 'cosign'
          
